// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwkbkwtlhtzrjktlntjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3a2Jrd3RsaHR6cmprdGxudGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjU5ODgsImV4cCI6MjA3MzMwMTk4OH0.KkcqzxrnPhTk16UFA_1CpMI_RuHGvGfErOOZpw6LKm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});